name: "Setup Yarn"
description: "Checkout code and install dependencies with yarn."
runs:
  using: "composite"
  steps:
    - name: "Enable corepack"
      shell: bash
      run: corepack enable

    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: "yarn"

    - name: "Install dependencies"
      shell: bash
      run: yarn install --immutable
